CREATE TABLE place (
    place_id VARCHAR(64) PRIMARY KEY,
    place_type VARCHAR(16) NOT NULL,
    name_kk VARCHAR(255) NOT NULL,
    name_ru VARCHAR(255) NOT NULL,
    source_name VARCHAR(255) NOT NULL,
    parent_region_id VARCHAR(64)
);

INSERT INTO place (place_id, place_type, name_kk, name_ru, source_name, parent_region_id)
VALUES
    ('aktau', 'CITY', 'Ақтау', 'Актау', 'Актау', 'mangystau'),
    ('aktobe', 'CITY', 'Ақтөбе', 'Актобе', 'Актобе', 'aktobe_region'),
    ('almaty', 'CITY', 'Алматы', 'Алматы', 'Алматы', NULL),
    ('arkalyk', 'CITY', 'Арқалық', 'Аркалык', 'Аркалык', 'kostanay_region'),
    ('arys', 'CITY', 'Арыс', 'Арыс', 'Арыс', 'turkistan_region'),
    ('astana', 'CITY', 'Астана', 'Астана', 'Астана', NULL),
    ('atyrau', 'CITY', 'Атырау', 'Атырау', 'Атырау', 'atyrau_region'),
    ('zhezkazgan', 'CITY', 'Жезқазған', 'Жезказган', 'Жезказган', 'ulytau'),
    ('karagandy', 'CITY', 'Қарағанды', 'Караганда', 'Караганда', 'karagandy_region'),
    ('kaskelen', 'CITY', 'Қаскелең', 'Каскелен', 'Каскелен', 'almaty_region'),
    ('kentau', 'CITY', 'Кентау', 'Кентау', 'Кентау', 'turkistan_region'),
    ('kokshetau', 'CITY', 'Көкшетау', 'Кокшетау', 'Кокшетау', 'aqmola'),
    ('qonaev', 'CITY', 'Қонаев', 'Конаев', 'Конаев', 'almaty_region'),
    ('kostanay', 'CITY', 'Қостанай', 'Костанай', 'Костанай', 'kostanay_region'),
    ('qosshy', 'CITY', 'Қосшы', 'Косшы', 'Косшы', 'aqmola'),
    ('kurchatov', 'CITY', 'Курчатов', 'Курчатов', 'Курчатов', 'abai_region'),
    ('kyzylorda', 'CITY', 'Қызылорда', 'Кызылорда', 'Кызылорда', 'kyzylorda_region'),
    ('pavlodar', 'CITY', 'Павлодар', 'Павлодар', 'Павлодар', 'pavlodar_region'),
    ('petropavl', 'CITY', 'Петропавл', 'Петропавловск', 'Петропавловск', 'north_kazakhstan'),
    ('saryagash', 'CITY', 'Сарыағаш', 'Сарыагаш', 'Сарыагаш', 'turkistan_region'),
    ('satbayev', 'CITY', 'Сәтбаев', 'Сатпаев', 'Сатпаев', 'ulytau'),
    ('semey', 'CITY', 'Семей', 'Семей', 'Семей', 'abai_region'),
    ('talgar', 'CITY', 'Талғар', 'Талгар', 'Талгар', 'almaty_region'),
    ('taldykorgan', 'CITY', 'Талдықорған', 'Талдыкорган', 'Талдыкорган', 'zhetysu'),
    ('taraz', 'CITY', 'Тараз', 'Тараз', 'Тараз', 'zhambyl'),
    ('tekeli', 'CITY', 'Текелі', 'Текели', 'Текели', 'zhetysu'),
    ('temirtau', 'CITY', 'Теміртау', 'Темиртау', 'Темиртау', 'karagandy_region'),
    ('turkistan', 'CITY', 'Түркістан', 'Туркестан', 'Туркестан', 'turkistan_region'),
    ('oral', 'CITY', 'Орал', 'Уральск', 'Уральск', 'west_kazakhstan'),
    ('oskemen', 'CITY', 'Өскемен', 'Усть-Каменогорск', 'Усть-Каменогорск', 'east_kazakhstan'),
    ('shu', 'CITY', 'Шу', 'Шу', 'Шу', 'zhambyl'),
    ('shymkent', 'CITY', 'Шымкент', 'Шымкент', 'Шымкент', NULL),
    ('ekibastuz', 'CITY', 'Екібастұз', 'Экибастуз', 'Экибастуз', 'pavlodar_region'),
    ('almaty_region', 'REGION', 'Алматы облысы', 'Алматинская область', 'Алматинская область', NULL),
    ('west_kazakhstan', 'REGION', 'Батыс Қазақстан облысы', 'Западно-Казахстанская область', 'Западно-Казахстанская область', NULL),
    ('kyzylorda_region', 'REGION', 'Қызылорда облысы', 'Кызылординская область', 'Кызылординская область', NULL),
    ('mangystau', 'REGION', 'Маңғыстау облысы', 'Мангистауская область', 'Мангистауская область', NULL),
    ('pavlodar_region', 'REGION', 'Павлодар облысы', 'Павлодарская область', 'Павлодарская область', NULL),
    ('north_kazakhstan', 'REGION', 'Солтүстік Қазақстан облысы', 'Северо-Казахстанская область', 'Северо-Казахстанская область', NULL),
    ('turkistan_region', 'REGION', 'Түркістан облысы', 'Туркестанская область', 'Туркестанская область', NULL),
    ('zhetysu', 'REGION', 'Жетісу облысы', 'область Жетысу', 'область Жетісу', NULL),
    ('tasboget', 'SETTLEMENT', 'Тасбөгет', 'Тасбогет', 'Тасбогет', 'kyzylorda_region'),
    ('karasai', 'DISTRICT', 'Қарасай ауданы', 'Карасайский район', 'Карасайский район', 'almaty_region'),
    ('sairam', 'DISTRICT', 'Сайрам ауданы', 'Сайрамский район', 'Сайрамский район', 'turkistan_region'),
    ('abai_village', 'VILLAGE', 'Абай', 'Абай', 'Абай', 'karagandy_region'),
    ('qyrgauyldy', 'VILLAGE', 'Қырғауылды', 'Кыргаулды', 'Кыргаулды', 'almaty_region'),
    ('pavlodarskoye', 'VILLAGE', 'Павлодарское', 'Павлодарское', 'Павлодарское', 'pavlodar_region'),
    ('chernoretsk', 'VILLAGE', 'Чернорецк', 'Чернорецк', 'Чернорецк', 'pavlodar_region'),
    ('abai_region', 'REGION', 'Абай облысы', 'Абайская область', 'Абайская область', NULL),
    ('aqmola', 'REGION', 'Ақмола облысы', 'Акмолинская область', 'Акмолинская область', NULL),
    ('aktobe_region', 'REGION', 'Ақтөбе облысы', 'Актюбинская область', 'Актюбинская область', NULL),
    ('atyrau_region', 'REGION', 'Атырау облысы', 'Атырауская область', 'Атырауская область', NULL),
    ('east_kazakhstan', 'REGION', 'Шығыс Қазақстан облысы', 'Восточно-Казахстанская область', 'Восточно-Казахстанская область', NULL),
    ('karagandy_region', 'REGION', 'Қарағанды облысы', 'Карагандинская область', 'Карагандинская область', NULL),
    ('kostanay_region', 'REGION', 'Қостанай облысы', 'Костанайская область', 'Костанайская область', NULL),
    ('ulytau', 'REGION', 'Ұлытау облысы', 'область Ұлытау', 'область Ұлытау', NULL),
    ('zhambyl', 'REGION', 'Жамбыл облысы', 'Жамбылская область', 'Жамбылская область', NULL);

ALTER TABLE place
    ADD CONSTRAINT fk_place_parent_region
    FOREIGN KEY (parent_region_id) REFERENCES place (place_id);
