CREATE TABLE candidate_content (
    candidate_content_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    candidate_id SMALLINT NOT NULL REFERENCES candidate (candidate_id) ON DELETE CASCADE,
    language VARCHAR(2) NOT NULL CHECK (language IN ('kk', 'ru')),
    section_type VARCHAR(32) NOT NULL CHECK (section_type IN (
        'OVERVIEW', 'BIOGRAPHY', 'EDUCATION', 'CAREER',
        'PUBLIC_ACTIVITY', 'POLICY_POSITION', 'OTHER'
    )),
    title TEXT NOT NULL,
    body_markdown TEXT NOT NULL,
    sort_order SMALLINT NOT NULL DEFAULT 0 CHECK (sort_order >= 0),
    review_status VARCHAR(16) NOT NULL CHECK (review_status IN ('DRAFT', 'REVIEWED', 'PUBLISHED')),
    reviewed_at TIMESTAMPTZ,
    content_hash CHAR(64) NOT NULL,
    source_revision VARCHAR(64) NOT NULL,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_candidate_content_section UNIQUE (candidate_id, language, section_type),
    CONSTRAINT ck_candidate_content_reviewed CHECK (
        review_status = 'DRAFT' OR reviewed_at IS NOT NULL
    )
);

CREATE INDEX ix_candidate_content_public
    ON candidate_content (candidate_id, language, sort_order)
    WHERE active AND review_status = 'PUBLISHED';

CREATE TABLE source (
    source_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_key VARCHAR(128) NOT NULL UNIQUE,
    source_type VARCHAR(32) NOT NULL CHECK (source_type IN (
        'OFFICIAL', 'NEWS', 'INTERVIEW', 'FACT_CHECK',
        'REPORT', 'SOCIAL_MEDIA', 'OTHER'
    )),
    publisher TEXT NOT NULL,
    title TEXT NOT NULL,
    original_url VARCHAR(2048) NOT NULL,
    canonical_url VARCHAR(2048) NOT NULL UNIQUE,
    language VARCHAR(8) NOT NULL,
    published_at TIMESTAMPTZ,
    retrieved_at TIMESTAMPTZ NOT NULL,
    archived_url VARCHAR(2048),
    content_hash CHAR(64) NOT NULL,
    source_revision VARCHAR(64) NOT NULL,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE candidate_source (
    candidate_id SMALLINT NOT NULL REFERENCES candidate (candidate_id) ON DELETE CASCADE,
    source_id BIGINT NOT NULL REFERENCES source (source_id) ON DELETE CASCADE,
    relationship_type VARCHAR(32) NOT NULL CHECK (relationship_type IN (
        'MEDIA_MENTION', 'INTERVIEW', 'PROFILE', 'OFFICIAL_RECORD', 'OTHER'
    )),
    is_primary_subject BOOLEAN NOT NULL DEFAULT FALSE,
    sort_order SMALLINT NOT NULL DEFAULT 0 CHECK (sort_order >= 0),
    verified_at TIMESTAMPTZ NOT NULL,
    review_status VARCHAR(16) NOT NULL DEFAULT 'DRAFT'
        CHECK (review_status IN ('DRAFT', 'REVIEWED', 'PUBLISHED')),
    reviewed_at TIMESTAMPTZ,
    content_hash CHAR(64) NOT NULL,
    source_revision VARCHAR(64) NOT NULL,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (candidate_id, source_id),
    CONSTRAINT ck_candidate_source_reviewed CHECK (
        review_status = 'DRAFT' OR reviewed_at IS NOT NULL
    )
);

CREATE INDEX ix_candidate_source_public
    ON candidate_source (candidate_id, relationship_type, sort_order)
    WHERE active AND review_status = 'PUBLISHED';

CREATE TABLE candidate_source_localization (
    candidate_id SMALLINT NOT NULL,
    source_id BIGINT NOT NULL,
    language VARCHAR(2) NOT NULL CHECK (language IN ('kk', 'ru')),
    summary TEXT NOT NULL,
    review_status VARCHAR(16) NOT NULL CHECK (review_status IN ('DRAFT', 'REVIEWED', 'PUBLISHED')),
    reviewed_at TIMESTAMPTZ,
    content_hash CHAR(64) NOT NULL,
    source_revision VARCHAR(64) NOT NULL,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (candidate_id, source_id, language),
    FOREIGN KEY (candidate_id, source_id)
        REFERENCES candidate_source (candidate_id, source_id) ON DELETE CASCADE,
    CONSTRAINT ck_candidate_source_localization_reviewed CHECK (
        review_status = 'DRAFT' OR reviewed_at IS NOT NULL
    )
);

CREATE INDEX ix_candidate_source_localization_public
    ON candidate_source_localization (candidate_id, language)
    WHERE active AND review_status = 'PUBLISHED';
