CREATE TABLE candidate_photo (
    candidate_photo_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    candidate_id SMALLINT NOT NULL REFERENCES candidate (candidate_id) ON DELETE CASCADE,
    photo_role VARCHAR(24) NOT NULL CHECK (photo_role IN (
        'PRIMARY', 'PARLIAMENT', 'PARTY_TEAM', 'WIKIMEDIA'
    )),
    r2_key VARCHAR(512) NOT NULL UNIQUE,
    thumb_r2_key VARCHAR(512) UNIQUE,
    width SMALLINT NOT NULL CHECK (width > 0),
    height SMALLINT NOT NULL CHECK (height > 0),
    byte_size INTEGER NOT NULL CHECK (byte_size > 0),
    content_type VARCHAR(32) NOT NULL CHECK (content_type IN (
        'image/jpeg', 'image/png', 'image/webp'
    )),
    source_kind VARCHAR(24) NOT NULL CHECK (source_kind IN (
        'PARTY_SITE', 'MAZHILIS', 'SENATE', 'WIKIMEDIA', 'OTHER'
    )),
    source_url VARCHAR(2048) NOT NULL,
    embedded_author TEXT,
    embedded_copyright TEXT,
    photo_taken DATE,
    rights_note TEXT NOT NULL,
    rights_cleared BOOLEAN NOT NULL DEFAULT FALSE,
    review_status VARCHAR(16) NOT NULL DEFAULT 'DRAFT' CHECK (review_status IN (
        'DRAFT', 'REVIEWED', 'PUBLISHED'
    )),
    reviewed_at TIMESTAMPTZ,
    content_hash CHAR(64) NOT NULL,
    source_revision VARCHAR(64) NOT NULL,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_candidate_photo_role UNIQUE (candidate_id, photo_role),
    CONSTRAINT ck_candidate_photo_reviewed CHECK (
        review_status = 'DRAFT' OR reviewed_at IS NOT NULL
    ),
    -- No collected portrait carries an explicit free-use licence: every source
    -- is "official, attribution preserved, no licence declared", and one Senate
    -- original asserted a photographer's copyright outright. Publishing
    -- therefore requires someone to clear rights explicitly rather than it
    -- happening by default.
    CONSTRAINT ck_candidate_photo_rights_gate CHECK (
        review_status <> 'PUBLISHED' OR rights_cleared
    )
);

-- The list view reads one row per candidate: the published primary photo.
CREATE INDEX ix_candidate_photo_public
    ON candidate_photo (candidate_id, photo_role)
    WHERE active AND review_status = 'PUBLISHED';
