-- Thematic measurement of the seven election programmes.
--
-- What this measures: ATTENTION — how much room a party gives a topic — never
-- its position on that topic and never the quality of the programme. A party
-- with a high T06 share wrote a lot about ecology; the measurement says nothing
-- about what it proposes to do.
--
-- Method: every programme was segmented into units and each unit hand-coded
-- against a published codebook. Reliability was established the standard way —
-- two annotators on a 175-unit pilot, Krippendorff alpha 0.827 for topic and
-- 0.852 for statement type — after which one annotator coded the whole corpus.

CREATE TABLE party_program_measurement (
    party_id VARCHAR(32) PRIMARY KEY REFERENCES political_party (party_id) ON DELETE CASCADE,
    -- Every unit the segmenter produced, including headings and slogans.
    units_total INTEGER NOT NULL CHECK (units_total > 0),
    -- Substantive units only. This is the divisor of every share below, and it
    -- is itself an annotation decision: where the boundary between a statement
    -- and a heading falls moves every share. It is stored so the UI can always
    -- show a share beside the number it was computed from.
    denominator INTEGER NOT NULL CHECK (denominator > 0),
    codebook_version VARCHAR(16) NOT NULL,
    CONSTRAINT denominator_within_total CHECK (denominator <= units_total)
);

COMMENT ON TABLE party_program_measurement IS
    'Per-party totals for the programme content analysis. Attention, not position.';

CREATE TABLE party_program_topic (
    party_program_topic_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    party_id VARCHAR(32) NOT NULL REFERENCES party_program_measurement (party_id) ON DELETE CASCADE,
    -- The codebook's vocabulary, listed rather than pattern-matched: a typo like
    -- 'T4' would satisfy a regex for the shape but name no topic.
    topic_code VARCHAR(4) NOT NULL CHECK (topic_code IN (
        'T00', 'T01', 'T02', 'T03', 'T04', 'T05', 'T06', 'T07', 'T08',
        'T09', 'T10', 'T11', 'T12', 'T13', 'T14', 'T15', 'T16', 'T99')),
    unit_count INTEGER NOT NULL CHECK (unit_count >= 0),
    -- Whether the code was covered by the two-annotator pilot. T15 (domestic and
    -- gender violence) and T16 (animal protection) entered the codebook after the
    -- pilot, so no agreement was ever measured for them and one annotator cannot
    -- produce any.
    pilot_verified BOOLEAN NOT NULL,
    -- NULL is not "missing" — it means the share must not be published. The bar
    -- on unpiloted codes is enforced here rather than left to whoever writes the
    -- next endpoint: an unverified code can carry a count, never a proportion.
    share NUMERIC(6, 5) CHECK (share >= 0 AND share <= 1),
    UNIQUE (party_id, topic_code),
    CONSTRAINT share_only_when_pilot_verified
        CHECK (pilot_verified = (share IS NOT NULL))
);

COMMENT ON COLUMN party_program_topic.share IS
    'NULL means the code did not pass the pilot: publish the count, never a share.';

CREATE TABLE party_program_statement_type (
    party_program_statement_type_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    party_id VARCHAR(32) NOT NULL REFERENCES party_program_measurement (party_id) ON DELETE CASCADE,
    -- PROBLEM: states a state of affairs as unsatisfactory.
    -- GOAL: a desired state, with no mechanism — this is a type, not vagueness.
    -- INSTRUMENT: a concrete measure, mechanism or bill.
    -- COMMITMENT: "we will", with the party as the subject.
    -- ACHIEVEMENT: a report on the party's own past work.
    -- DESCRIPTION: neutral context, statistics, history.
    statement_type VARCHAR(16) NOT NULL CHECK (statement_type IN (
        'PROBLEM', 'GOAL', 'INSTRUMENT', 'COMMITMENT', 'ACHIEVEMENT', 'DESCRIPTION')),
    unit_count INTEGER NOT NULL CHECK (unit_count >= 0),
    share NUMERIC(6, 5) NOT NULL CHECK (share >= 0 AND share <= 1),
    UNIQUE (party_id, statement_type)
);

COMMENT ON TABLE party_program_statement_type IS
    'How a party writes, not what about: a promise, a mechanism and a diagnosis of the same topic are different statements and must not be pooled.';

CREATE INDEX party_program_topic_topic_idx ON party_program_topic (topic_code);
