#!/usr/bin/env python3
"""Generate the Flyway candidate table and seed migration."""
import csv
import os

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
INPUT = os.path.join(ROOT, "data", "candidates_classified.csv")
OUTPUT = os.path.join(
    ROOT, "backend", "src", "main", "resources", "db", "migration",
    "V3__create_candidate.sql",
)


def quote(value):
    return "'" + value.replace("'", "''") + "'"


def boolean(value):
    if value not in {"true", "false"}:
        raise ValueError(f"invalid boolean: {value!r}")
    return value.upper()


def main():
    with open(INPUT, newline="", encoding="utf-8") as f:
        rows = list(csv.DictReader(f))

    invalid_genders = [
        f"{row['party_id']}:{row['order']}={row['gender_guess']!r}"
        for row in rows if row["gender_guess"] not in {"M", "F"}
    ]
    if invalid_genders:
        raise SystemExit("invalid reviewed genders: " + ", ".join(invalid_genders))

    lines = [
        "CREATE TABLE candidate (",
        "    candidate_id SMALLINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,",
        "    party_id VARCHAR(32) NOT NULL REFERENCES political_party (party_id),",
        "    list_order SMALLINT NOT NULL,",
        "    surname VARCHAR(255) NOT NULL,",
        "    given_names VARCHAR(255) NOT NULL,",
        "    birth_year SMALLINT NOT NULL,",
        "    gender CHAR(1) NOT NULL CHECK (gender IN ('M', 'F')),",
        "    position_raw TEXT NOT NULL,",
        "    position_kk TEXT NOT NULL,",
        "    position_ru TEXT NOT NULL,",
        "    residence_raw TEXT NOT NULL,",
        "    place_id VARCHAR(64) NOT NULL REFERENCES place (place_id),",
        "    sector VARCHAR(32) NOT NULL,",
        "    employer_type VARCHAR(32) NOT NULL,",
        "    is_party_insider BOOLEAN NOT NULL,",
        "    seniority VARCHAR(32) NOT NULL,",
        "    is_incumbent BOOLEAN NOT NULL,",
        "    CONSTRAINT uq_candidate_party_order UNIQUE (party_id, list_order)",
        ");",
        "",
        "INSERT INTO candidate (",
        "    party_id, list_order, surname, given_names, birth_year, gender,",
        "    position_raw, position_kk, position_ru, residence_raw, place_id, sector,",
        "    employer_type, is_party_insider, seniority, is_incumbent",
        ")",
        "VALUES",
    ]

    for index, row in enumerate(rows):
        suffix = ";" if index == len(rows) - 1 else ","
        values = [
            quote(row["party_id"]), row["order"], quote(row["surname"]),
            quote(row["given_names"]), row["birth_year"], quote(row["gender_guess"]),
            quote(row["position_raw"]), quote(row["position_kk"]),
            quote(row["position_ru"]), quote(row["residence_raw"]),
            quote(row["place_id"]), quote(row["sector"]),
            quote(row["employer_type"]), boolean(row["is_party_insider"]),
            quote(row["seniority"]), boolean(row["is_incumbent"]),
        ]
        lines.append("    (" + ", ".join(values) + ")" + suffix)

    with open(OUTPUT, "w", encoding="utf-8", newline="\n") as f:
        f.write("\n".join(lines) + "\n")
    print(f"Wrote {len(rows)} rows -> {OUTPUT}")


if __name__ == "__main__":
    main()
