#!/usr/bin/env python3
"""Generate the V9 seed from the annotation aggregate.

Hand-transcribing 7 parties × 18 topics × 6 statement types would be a hundred
chances to introduce a typo into published numbers, so the seed is generated from
program_topic_metrics.json — the same file the report renders from. Re-run it
after any re-annotation; the migration is meant to be regenerated, not edited.

    python3 scripts/generate_program_measurement_seed.py
"""

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
WORK = ROOT / "data" / "work"
OUT = (ROOT / "backend/src/main/resources/db/migration"
       / "V9__seed_party_program_measurement.sql")
CODEBOOK_VERSION = "1.7"
# T15 and T16 entered the codebook after the two-annotator pilot, so no agreement
# was ever measured for them and one annotator cannot produce any. They carry a
# count and never a share; the schema enforces the pairing.
UNPILOTED = {"T15", "T16"}
TYPES = {"problem": "PROBLEM", "goal": "GOAL", "instrument": "INSTRUMENT",
         "commitment": "COMMITMENT", "achievement": "ACHIEVEMENT",
         "description": "DESCRIPTION"}


def main():
    data = json.loads((WORK / "program_topic_metrics.json").read_text(encoding="utf-8"))
    per = data["per_party"]
    parties = sorted(per, key=lambda p: -per[p]["denominator"])

    lines = [
        "-- Generated by scripts/generate_program_measurement_seed.py — do not edit by hand.",
        "-- Source: data/work/program_topic_metrics.json, itself aggregated from the",
        "-- per-unit annotations in data/work/annotations/.",
        "--",
        f"-- Codebook {CODEBOOK_VERSION}, frozen for the duration of the coding; borderline",
        "-- decisions went to data/work/annotation_precedents.md instead of rule changes.",
        "",
        "INSERT INTO party_program_measurement "
        "(party_id, units_total, denominator, codebook_version) VALUES",
    ]
    rows = [f"    ('{p}', {per[p]['units_total']}, {per[p]['denominator']}, "
            f"'{CODEBOOK_VERSION}')" for p in parties]
    lines.append(",\n".join(rows) + ";")
    lines.append("")

    lines.append("INSERT INTO party_program_topic "
                 "(party_id, topic_code, unit_count, pilot_verified, share) VALUES")
    topic_rows = []
    for party in parties:
        counts = per[party]["topic_counts"]
        shares = per[party]["topic_shares"]
        for topic in sorted(counts):
            verified = topic not in UNPILOTED
            share = f"{shares[topic]:.5f}" if verified else "NULL"
            topic_rows.append(
                f"    ('{party}', '{topic}', {counts[topic]}, "
                f"{'TRUE' if verified else 'FALSE'}, {share})")
    lines.append(",\n".join(topic_rows) + ";")
    lines.append("")

    lines.append("INSERT INTO party_program_statement_type "
                 "(party_id, statement_type, unit_count, share) VALUES")
    type_rows = []
    for party in parties:
        counts = per[party]["type_counts"]
        shares = per[party]["type_shares"]
        for kind, code in TYPES.items():
            if kind not in counts:
                continue
            type_rows.append(
                f"    ('{party}', '{code}', {counts[kind]}, {shares[kind]:.5f})")
    lines.append(",\n".join(type_rows) + ";")
    lines.append("")

    body = "\n".join(lines)

    # Refuse to overwrite a migration that already exists. V9 has been applied in
    # every environment, and rewriting an applied migration changes its checksum
    # and breaks Flyway validation — the state V4 and V5 are still stuck in. This
    # guard exists because the script did exactly that once, silently.
    if OUT.exists() and OUT.read_text(encoding="utf-8") != body:
        print(f"REFUSING to overwrite {OUT.relative_to(ROOT)} — it is already applied.")
        print("After a re-annotation, either point OUT at a new version, or write an")
        print("UPDATE migration correcting the rows that changed (see V16).")
        raise SystemExit(1)

    OUT.write_text(body, encoding="utf-8")
    unpiloted = sum(1 for p in parties for t in per[p]["topic_counts"] if t in UNPILOTED)
    print(f"wrote {OUT.relative_to(ROOT)}")
    print(f"  {len(parties)} parties, {len(topic_rows)} topic rows "
          f"({unpiloted} without a publishable share), {len(type_rows)} type rows")


if __name__ == "__main__":
    main()
